---
- name: Install Python Dependencies
  pip:
    name:
      - django-auth-ldap
      - pyldap
      - psycopg2
      - Constellation-Base
    state: latest
    virtualenv: /opt/constellation/venv
    virtualenv_python: python3

- name: Install Constellation Modules
  pip:
    name: "{{ item.url | default(item.name) }}"
    state: present
    virtualenv: /opt/constellation/venv
    virtualenv_python: python3
  with_items: "{{ ConstellationApps }}"
  loop_control:
    label: "{{ item.name }}"

- name: Install Dynamic Constellation Site Settings
  template:
    src: "{{ item }}.py.j2"
    dest: /opt/constellation/constellation/{{ item }}.py
    owner: constellation
    group: constellation
    mode: 0644
  with_items:
    - settings
    - urls
  notify:
    - constellation_migrate
    - constellation_collectstatic
    - constellation

- name: Install Static Constellation Site Settings
  copy:
    src: "{{ item }}.py"
    dest: /opt/constellation/constellation/{{ item }}.py
    owner: constellation
    group: constellation
    mode: 0644
  with_items:
    - wsgi
    - __init__
  notify:
    - constellation_migrate
    - constellation_collectstatic
    - constellation

- name: Install uwsgi.ini
  copy:
    src: uwsgi.ini
    dest: /opt/constellation/uwsgi.ini
    owner: constellation
    group: constellation
    mode: 0644
