---
- name: constellation_migrate
  command: /opt/constellation/scripts/do_migrate
  become_user: constellation

- name: constellation_collectstatic
  command: /opt/constellation/scripts/do_collectstatic

- name: constellation
  command: sv restart constellation
