---
- name: constellation_migrate
  command: /opt/constellation/scripts/do_migrate

- name: constellation_collectstatic
  command: /opt/constellation/scripts/do_collectstatic

- name: constellation
  debug:
    msg: You must restart the constellation service
